import { ISO, ROCK_LOOKS } from '@render/index';
import type { BlockedLabel, EffectDef, VfxCue, VfxLimits } from './types';

/** Same blocked cue plays at most once per this many ms (the game can re-emit every tick). */
export const BLOCKED_THROTTLE_MS = 600;

/** Game event type -> cues to play. New events are new entries here. */
export const EVENT_VFX: Readonly<Record<string, readonly VfxCue[]>> = {
  itemGathered: [
    { effect: 'logPuff', at: 'node', when: { skill: 'woodcutting' } },
    { effect: 'oreSparkle', at: 'node', when: { skill: 'mining' }, tintField: 'itemId' },
    { effect: 'catchSplash', at: 'node', when: { skill: 'fishing' } },
    { effect: 'catchRing', at: 'node', when: { skill: 'fishing' } },
  ],
  // Needs `nodeId` on the event (the scene adds it from the gathering session).
  // No skill on the event counts as woodcutting (the axe swing predates the tag).
  swingImpact: [
    { effect: 'woodChips', at: 'node', towardPlayer: 6, unless: { skill: 'mining' } },
    { effect: 'barkFlakes', at: 'node', towardPlayer: 8, unless: { skill: 'mining' } },
    { effect: 'leafDrift', at: 'node', unless: { skill: 'mining' } },
    { effect: 'rockDust', at: 'node', when: { skill: 'mining' } },
    { effect: 'stoneChips', at: 'node', when: { skill: 'mining' } },
  ],
  fishingStarted: [
    { effect: 'castSplash', at: 'node' },
    { effect: 'castRing', at: 'node' },
  ],
  spotMoved: [
    { effect: 'spotRipple', at: 'from' },
    { effect: 'spotRippleOuter', at: 'from' },
    { effect: 'spotRipple', at: 'to' },
    { effect: 'spotRippleOuter', at: 'to' },
  ],
  // Firemaking/cooking events carry `tile` ({x, y}); no tile = nothing plays.
  fireLightStarted: [
    { effect: 'strikeSparks', at: 'tile' },
    { effect: 'lightWisp', at: 'tile' },
  ],
  fireLit: [
    { effect: 'ignitionBloom', at: 'tile' },
    { effect: 'ignitionGlow', at: 'tile' },
    { effect: 'ignitionSparks', at: 'tile' },
    { effect: 'fireSmoke', at: 'tile', persist: { action: 'start', keyField: 'fireId' } },
  ],
  fireBurnedOut: [
    { effect: 'fireSmoke', at: 'tile', persist: { action: 'stop', keyField: 'fireId' } },
    { effect: 'emberFade', at: 'tile' },
    { effect: 'ashPuff', at: 'tile' },
  ],
  itemCooked: [
    { effect: 'steamPuff', at: 'tile', when: { burnt: false } },
    { effect: 'burntSmoke', at: 'tile', when: { burnt: true } },
    { effect: 'burntFlecks', at: 'tile', when: { burnt: true } },
  ],
  // cookingStopped: no cue (stopping is silent).
  xpGained: [{ effect: 'xpDrop', at: 'player' }],
  levelUp: [
    { effect: 'levelUpRing', at: 'player' },
    { effect: 'levelUpSparkle', at: 'player' },
  ],
  nodeDepleted: [
    { effect: 'treeFallDust', at: 'node', unless: { skill: 'mining' } },
    { effect: 'leafBurst', at: 'node', unless: { skill: 'mining' } },
    { effect: 'rockBurst', at: 'node', when: { skill: 'mining' } },
    { effect: 'rockPebbles', at: 'node', when: { skill: 'mining' } },
  ],
  // gatherStopped: depleted / cancelled / unknown reasons match no cue and play nothing.
  gatherStopped: [
    {
      effect: 'blockedCross',
      at: 'node',
      when: { reason: 'levelTooLow' },
      throttleMs: BLOCKED_THROTTLE_MS,
    },
    {
      effect: 'blockedText',
      at: 'player',
      when: { reason: 'levelTooLow' },
      throttleMs: BLOCKED_THROTTLE_MS,
    },
    {
      effect: 'blockedCross',
      at: 'node',
      when: { reason: 'noTool' },
      throttleMs: BLOCKED_THROTTLE_MS,
    },
    {
      effect: 'blockedText',
      at: 'player',
      when: { reason: 'noTool' },
      throttleMs: BLOCKED_THROTTLE_MS,
    },
    {
      effect: 'blockedText',
      at: 'player',
      when: { reason: 'inventoryFull' },
      throttleMs: BLOCKED_THROTTLE_MS,
    },
    {
      effect: 'blockedText',
      at: 'player',
      when: { reason: 'noBait' },
      throttleMs: BLOCKED_THROTTLE_MS,
    },
  ],
};

/** Label per gatherStopped reason. `withField` wins when the event carries that field. */
export const BLOCKED_TEXT: Readonly<Record<string, BlockedLabel>> = {
  levelTooLow: {
    text: 'Level too low',
    withField: { field: 'requiredLevel', text: 'Level {value} needed' },
  },
  noTool: { text: 'No axe', withField: { field: 'tool', text: 'No {value}' } },
  inventoryFull: { text: 'Inventory full' },
  noBait: { text: 'No bait' },
};

/** Ore item id -> sparkle colour. Colours come from the rock art so they always match the vein. */
export const ITEM_TINT: Readonly<Record<string, number>> = {
  copper_ore: ROCK_LOOKS.copper_rock.ore,
  tin_ore: ROCK_LOOKS.tin_rock.ore,
  iron_ore: ROCK_LOOKS.iron_rock.ore,
  coal: ROCK_LOOKS.coal_rock.ore,
};

const WATER = [0x9fd4f0, 0xd6eefb, 0x6fb6e0] as const;

export const EFFECTS: Readonly<Record<string, EffectDef>> = {
  woodChips: {
    kind: 'burst',
    layer: 'world',
    lift: 24,
    decorative: true,
    count: 6,
    colors: [0x8b5a2b, 0x6b4423, 0xa8772f],
    size: [3, 5],
    spread: 16,
    rise: 14,
    fall: 10,
    lifeMs: 450,
    jitter: 4,
  },
  logPuff: {
    kind: 'burst',
    layer: 'world',
    lift: 22,
    decorative: true,
    count: 4,
    colors: [0xa8772f, 0xc99a52],
    size: [2, 4],
    spread: 10,
    rise: 14,
    fall: 6,
    lifeMs: 380,
    jitter: 3,
  },
  barkFlakes: {
    kind: 'burst',
    layer: 'world',
    lift: 26,
    decorative: true,
    count: 4,
    colors: [0x5a3b1e, 0x4a2f17, 0x6e4a26],
    size: [2, 3],
    spread: 20,
    rise: 8,
    fall: 14,
    lifeMs: 500,
    jitter: 3,
  },
  leafDrift: {
    kind: 'burst',
    layer: 'world',
    lift: 64,
    decorative: true,
    count: 3,
    colors: [0x4f8f3a, 0x6aa84f, 0x3d7a2e],
    size: [3, 4],
    spread: 20,
    rise: 2,
    fall: 40,
    lifeMs: 900,
    jitter: 14,
  },
  leafBurst: {
    kind: 'burst',
    layer: 'world',
    lift: 52,
    decorative: true,
    count: 10,
    colors: [0x4f8f3a, 0x6aa84f, 0x3d7a2e, 0x86b85a],
    size: [3, 5],
    spread: 30,
    rise: 8,
    fall: 44,
    lifeMs: 950,
    jitter: 16,
  },
  treeFallDust: {
    kind: 'burst',
    layer: 'world',
    lift: 6,
    decorative: true,
    count: 8,
    colors: [0xc8b89a, 0xb3a384, 0xd9cdb4],
    size: [4, 8],
    spread: 24,
    rise: 6,
    fall: -4,
    lifeMs: 650,
    round: true,
    jitter: 10,
  },
  rockDust: {
    kind: 'burst',
    layer: 'world',
    lift: 12,
    decorative: true,
    count: 5,
    colors: [0xb9aea0, 0xcfc6ba, 0x9d9388],
    size: [4, 7],
    spread: 14,
    rise: 6,
    fall: -6,
    lifeMs: 520,
    round: true,
    jitter: 8,
  },
  stoneChips: {
    kind: 'burst',
    layer: 'world',
    lift: 18,
    decorative: true,
    count: 4,
    colors: [0x7a7068, 0x5d554f, 0x978c82],
    size: [2, 4],
    spread: 18,
    rise: 16,
    fall: 10,
    lifeMs: 420,
    jitter: 5,
  },
  oreSparkle: {
    kind: 'burst',
    layer: 'overhead',
    lift: 30,
    decorative: true,
    count: 7,
    colors: [0xffffff],
    size: [3, 4],
    spread: 16,
    rise: 22,
    fall: -6,
    lifeMs: 600,
    jitter: 6,
  },
  rockBurst: {
    kind: 'burst',
    layer: 'world',
    lift: 10,
    decorative: true,
    count: 12,
    colors: [0xb9aea0, 0xcfc6ba, 0x9d9388, 0x857b72],
    size: [5, 10],
    spread: 32,
    rise: 8,
    fall: -8,
    lifeMs: 750,
    round: true,
    jitter: 12,
  },
  rockPebbles: {
    kind: 'burst',
    layer: 'world',
    lift: 30,
    decorative: true,
    count: 6,
    colors: [0x6b625b, 0x544d47, 0x8a8077],
    size: [3, 6],
    spread: 22,
    rise: 4,
    fall: 30,
    lifeMs: 600,
    jitter: 10,
  },
  castSplash: {
    kind: 'burst',
    layer: 'world',
    lift: 6,
    decorative: true,
    count: 5,
    colors: WATER,
    size: [2, 3],
    spread: 10,
    rise: 14,
    fall: 4,
    lifeMs: 450,
    round: true,
    jitter: 4,
  },
  castRing: {
    kind: 'ring',
    layer: 'ground',
    squashY: 0.5,
    color: 0xcfeaf8,
    radius: [3, 16],
    width: 2,
    lifeMs: 550,
  },
  catchSplash: {
    kind: 'burst',
    layer: 'world',
    lift: 10,
    decorative: true,
    count: 10,
    colors: WATER,
    size: [2, 4],
    spread: 18,
    rise: 28,
    fall: 4,
    lifeMs: 650,
    round: true,
    jitter: 5,
  },
  catchRing: {
    kind: 'ring',
    layer: 'ground',
    squashY: 0.5,
    color: 0xeaf6fd,
    radius: [4, 22],
    width: 2,
    lifeMs: 650,
  },
  spotRipple: {
    kind: 'ring',
    layer: 'ground',
    squashY: 0.5,
    color: 0xbfe3f5,
    radius: [4, 20],
    width: 2,
    lifeMs: 800,
  },
  spotRippleOuter: {
    kind: 'ring',
    layer: 'ground',
    squashY: 0.5,
    color: 0x8fcbe8,
    radius: [8, 30],
    width: 1,
    lifeMs: 1100,
  },
  levelUpSparkle: {
    kind: 'burst',
    layer: 'overhead',
    lift: 40,
    decorative: true,
    count: 12,
    colors: [0xffe14d, 0xffffff, 0xffb830],
    size: [2, 4],
    spread: 30,
    rise: 34,
    fall: -10,
    lifeMs: 800,
    jitter: 6,
  },
  levelUpRing: {
    kind: 'ring',
    layer: 'ground',
    squashY: 0.5,
    color: 0xffe14d,
    radius: [10, 48],
    width: 3,
    lifeMs: 600,
  },
  // Firemaking: tinderbox strikes (3 lighting ticks of 600 ms), a faint wisp, then the flare and the fire.
  strikeSparks: {
    kind: 'burst',
    layer: 'world',
    lift: 8,
    decorative: true,
    additive: true,
    count: 6,
    colors: [0xfff4b0, 0xffe27a, 0xffffff],
    size: [1.5, 2.5],
    spread: 12,
    rise: 14,
    fall: 8,
    lifeMs: 350,
    jitter: 3,
    repeat: { times: 3, everyMs: 600 },
  },
  lightWisp: {
    kind: 'burst',
    layer: 'world',
    lift: 10,
    decorative: true,
    count: 1,
    colors: [0xd8d8d8, 0xc4c4c4],
    size: [5, 8],
    spread: 2,
    rise: 0,
    fall: -26,
    lifeMs: 1100,
    round: true,
    alpha: 0.3,
    grow: 2.2,
    drift: 3,
    jitter: 2,
    repeat: { times: 3, everyMs: 600 },
  },
  ignitionBloom: {
    kind: 'burst',
    layer: 'world',
    lift: 12,
    decorative: true,
    additive: true,
    count: 1,
    colors: [0xfff1b8],
    size: [22, 26],
    spread: 0,
    rise: 0,
    fall: 0,
    lifeMs: 260,
    round: true,
    alpha: 0.85,
    grow: 1.9,
    jitter: 0,
  },
  ignitionGlow: {
    kind: 'burst',
    layer: 'ground',
    lift: 4,
    decorative: true,
    additive: true,
    count: 1,
    colors: [0xff8a2a],
    size: [34, 38],
    spread: 0,
    rise: 0,
    fall: 0,
    lifeMs: 520,
    round: true,
    alpha: 0.5,
    grow: 1.6,
    jitter: 0,
  },
  ignitionSparks: {
    kind: 'burst',
    layer: 'world',
    lift: 14,
    decorative: true,
    additive: true,
    count: 14,
    colors: [0xffd24a, 0xff9a2e, 0xfff4b0],
    size: [1.5, 3],
    spread: 24,
    rise: 30,
    fall: 6,
    lifeMs: 650,
    jitter: 5,
  },
  fireSmoke: {
    kind: 'fire',
    layer: 'world',
    lift: 0,
    decorative: true,
    tickMs: 320,
    smokeLayer: 'overhead',
    smokeLift: 22,
    smoke: {
      colors: [0x8e8e8e, 0xa6a6a6, 0x7a7a7a],
      size: [5, 8],
      rise: 56,
      drift: 8,
      sway: 6,
      lifeMs: 2000,
      alpha: 0.4,
      grow: 2.6,
    },
    emberChance: 0.3,
    ember: {
      colors: [0xffb347, 0xff8a2a, 0xffd27a],
      size: [1.5, 2.5],
      rise: 44,
      sway: 8,
      lifeMs: 1300,
    },
  },
  emberFade: {
    kind: 'burst',
    layer: 'world',
    lift: 10,
    decorative: true,
    additive: true,
    count: 8,
    colors: [0xff9a2e, 0xff6a1a, 0xffd27a],
    size: [1.5, 2.5],
    spread: 14,
    rise: 0,
    fall: -36,
    lifeMs: 1400,
    jitter: 6,
  },
  ashPuff: {
    kind: 'burst',
    layer: 'ground',
    lift: 4,
    decorative: true,
    count: 5,
    colors: [0xb8b4ac, 0x9c9890, 0x7f7b75],
    size: [4, 7],
    spread: 12,
    rise: 2,
    fall: -8,
    lifeMs: 700,
    round: true,
    alpha: 0.6,
    jitter: 6,
  },
  // Cooking: pale steam on success, dark smoke + flecks on a burn. Rises from just above the fire.
  steamPuff: {
    kind: 'burst',
    layer: 'overhead',
    lift: 30,
    decorative: true,
    count: 5,
    colors: [0xffffff, 0xf0f0f0, 0xe2e2e2],
    size: [5, 9],
    spread: 5,
    rise: 0,
    fall: -34,
    lifeMs: 900,
    round: true,
    alpha: 0.7,
    grow: 2.4,
    drift: 5,
    jitter: 5,
  },
  burntSmoke: {
    kind: 'burst',
    layer: 'overhead',
    lift: 30,
    decorative: true,
    count: 6,
    colors: [0x2e2e2e, 0x3d3d3d, 0x4a4a4a],
    size: [6, 10],
    spread: 6,
    rise: 0,
    fall: -40,
    lifeMs: 1100,
    round: true,
    alpha: 0.75,
    grow: 2.6,
    drift: 6,
    jitter: 5,
  },
  burntFlecks: {
    kind: 'burst',
    layer: 'world',
    lift: 26,
    decorative: true,
    count: 4,
    colors: [0x1e1e1e, 0x2a2420, 0x3a312b],
    size: [1.5, 3],
    spread: 16,
    rise: 14,
    fall: 10,
    lifeMs: 550,
    jitter: 4,
  },
  xpDrop: {
    kind: 'xpDrop',
    layer: 'overhead',
    lift: 56,
    riseY: 34,
    lifeMs: 1100,
    fontPx: 14,
    defaultColor: '#ffffff',
  },
  clickMarker: {
    kind: 'marker',
    layer: 'ground',
    colors: { walk: 0xffee33, interact: 0xff3b30 },
    halfW: ISO.tileWidth / 2,
    halfH: ISO.tileHeight / 2,
    lifeMs: 450,
  },
  blockedCross: {
    kind: 'cross',
    layer: 'world',
    lift: 24,
    color: 0xff3b30,
    half: 9,
    fromScale: 0.5,
    toScale: 1.3,
    lifeMs: 500,
  },
  blockedText: {
    kind: 'blockedText',
    layer: 'overhead',
    lift: 56,
    color: '#ff5a4d',
    fontPx: 14,
    riseY: 14,
    lifeMs: 1000,
    shakePx: 3,
    shakeMs: 50,
    shakes: 3,
  },
};

/** Short XP-drop tag per skill (colour comes from core/progression via createVfx's `skillColor`). Unknown skills use the first 3 letters. */
export const SKILL_TAG: Readonly<Record<string, string>> = {
  woodcutting: 'WC',
  mining: 'MN',
  fishing: 'FS',
  cooking: 'CK',
  smithing: 'SM',
  crafting: 'CR',
};

/** 'reduced' mode shortens kept effects to this fraction of their duration (and removes burst jitter). */
export const REDUCED_LIFE_SCALE = 0.6;

/**
 * Caps. Phones get the smaller set, chosen by data (pass to createVfx).
 * Rings: a spot hop needs 4 (2 ends x 2 rings) and the world has 4 spots, whose hops can overlap, so a
 * phone needs 16 or the earlier ends are recycled mid-ripple.
 */
export const LIMITS_DESKTOP: VfxLimits = {
  texts: 20,
  particles: 64,
  fires: 8,
  fireParticles: 14,
  rings: 24,
  markers: 4,
};
export const LIMITS_MOBILE: VfxLimits = {
  texts: 12,
  particles: 32,
  fires: 4,
  fireParticles: 6,
  rings: 16,
  markers: 3,
};

/** Drops spawned within this window stack upward instead of overlapping. */
export const XP_STACK_WINDOW_MS = 700;
export const XP_STACK_LINE_PX = 16;
